### ISSUE TITLE
Javascript function is not published to cluster with "publish to azure" (VSCode) 

### ISSUE THREAD

**Issue by oising** [Azure/azure-stream-analytics#108] opened 2022-01-27 15:38 UTC
Hello @Fleid ;) 

We noticed this morning that when publishing our custom deserializer project to an ASA cluster in Azure, our JS function is not published. We have to create it by hand in the azure portal. Is this a known issue? When running locally, everything seems fine (the function is available and is available within the asa sql.)

Is this a known issue? Let me know if you want me to send you a zip of our workspace/solution, and how.

**Comment by Fleid** [comment] 2022-01-27 16:56
Hi @oising, what tool did you use to publish your project here? Is that VS, VS Code or something else? Thanks!

**Comment by oising** [comment] 2022-01-27 17:47
VS code.

**Comment by Fleid** [comment] 2022-01-28 22:14
We created a bug on our side, but can't reproduce yet. I'll try asap.

**Comment by oising** [comment] 2022-01-29 00:38
@Fleid I can send you the VS code workspace and projects, if you want.

**Comment by oising** [comment] 2022-01-29 17:10
It looks like your ASA extension in VS and VS Code are incompatible or are using incorrect config, or are just broken. 

![image](https://user-images.githubusercontent.com/1844001/151670267-dbfb772f-46e2-450a-a06f-2a467416a6c0.png)

As you can see, one of the SDKs used JSFunctionConfig as a subtype (WRONG), and the other uses JSFunction (CORRECT.)

These were machine generated configs, nothing done by hand. Maybe with this you can figure out the bug.

**Comment by Fleid** [comment] 2022-01-31 23:21
Could you please send me the project at askasa@microsoft.com?
Thanks!

**Comment by Fleid** [comment] 2022-01-31 23:22
VS and VS Code don't generate the same config files, that's more or less expected. Not sure it's related to your issue.

**Comment by Fleid** [comment] 2022-02-01 22:50
Hi @oising, I tried to reproduce this morning and could not.
I'm even deleting my UDF from the portal and still get it recreated when republishing my job (that uses both a UDF and a custom deserializer).

**Comment by oising** [comment] 2022-02-02 15:57
@Fleid -- more to the point, do you see my screenshot above? One of the IDEs (I don't know which) generated a subType of "JSFunctionConfig" and the other generated "JSFunction" in the asaproj.json -- but only **one** is recognized by ASA, but both are fine in the IDE. This is the real problem.

**Comment by Fleid** [comment] 2022-02-07 18:16
There are two things here:
- If the entire project life cycle is in VS Code, does the bug happen? Here neither the dev owner or me were able to reproduce the issue. Can you confirm you get that behavior on a project that was only ever edited in VS Code?
- What if the project was opened / edited both in VS Code and VS. Then it's another issue, because as I mentioned the config files are not expected to be following the same convention. Let me know if the issue is scoped on that scenario and I'll follow up internally

**Comment by oising** [comment] 2022-02-07 20:38
I think the project might have been created in Code and then opened later in VS, or vice-versa. I couldn't tell you, honestly. One thing for sure is that the asaproj.json was *not* hand-edited.

**Comment by Fleid** [comment] 2022-03-08 03:36
Hi @oising, we are going to close this issue, as we were not able to reproduce the issue when developing with a single IDE. Our intuition is that going from one to the other broke the config files. Our recommendation is to use VS Code, and always open your solution with VS Code.

**Closed by Fleid** 2022-03-08 03:36 UTC
